### ISSUE TITLE
Gpu memory leak

### ISSUE THREAD

**Issue by VenkatLohithDasari** [Extraltodeus/depthmap2mask#16]
Hey, As I constantly Generate Images. I see slow growth in GPU Memory, after generating around 10 images, GPU memory is 100% full. After that, It always Throws OOM Error..

I mainly use two models, one is MiDas_v21 and other is dpt_large. Doesn't matter which model it is.

**Comment by flufy3d** [comment]
I have same issue ,when I switch the depth gen model MiDas_v21 to small or to large

**Comment by iterhating** [comment]
I came here to make a similar comment: after a run using depthmap2mask the memory allocated during the run is not released, this is clearly visible in a resource monitor looking at the VRAM usage, and reproducible across two machines and several different attempts. Commanline flags include --medvram, --full precision, and --no-halfs

The same thing happens with the depth mask script [here ](https://github.com/thygate/stable-diffusion-webui-depthmap-script), since they both use MiDAs, I'm guess that might be the common source for the error.

**Comment by Extraltodeus** [comment]
Ok so it appears that midas ads up to the GPU's memory after each use indeed.
![image](https://user-images.githubusercontent.com/15731540/205502575-bd3158c5-4057-4416-8bab-cbc656d34b05.png)

**Comment by Extraltodeus** [comment]
the merge is done, thank you @TingTingin
